import { PlayerModel } from "../../models/player-model";

export const allPlayers: PlayerModel[] = [
  {
    id: 1,
    name: "Lionel Messi",
    club: "Paris Saint-Germain",
    nationality: "Argentina",
    position: "Forward",
    statistics: {
      Overall: 94,
      Pace: 85,
      Shooting: 95,
      Passing: 92,
      Dribbling: 96,
      Defending: 32,
      Physical: 70,
    },
  },
  {
    id: 2,
    name: "Cristiano Ronaldo",
    club: "Manchester United",
    nationality: "Portugal",
    position: "Forward",
    statistics: {
      Overall: 92,
      Pace: 88,
      Shooting: 93,
      Passing: 81,
      Dribbling: 89,
      Defending: 38,
      Physical: 85,
    },
  },
  {
    id: 3,
    name: "Kevin De Bruyne",
    club: "Manchester City",
    nationality: "Belgium",
    position: "Midfielder",
    statistics: {
      Overall: 91,
      Pace: 76,
      Shooting: 88,
      Passing: 94,
      Dribbling: 89,
      Defending: 65,
      Physical: 83,
    },
  },
  {
    id: 4,
    name: "Virgil van Dijk",
    club: "Liverpool",
    nationality: "Netherlands",
    position: "Defender",
    statistics: {
      Overall: 90,
      Pace: 77,
      Shooting: 60,
      Passing: 82,
      Dribbling: 70,
      Defending: 93,
      Physical: 88,
    },
  },
  {
    id: 5,
    name: "Kylian Mbappe",
    club: "Paris Saint-Germain",
    nationality: "France",
    position: "Forward",
    statistics: {
      Overall: 93,
      Pace: 96,
      Shooting: 87,
      Passing: 81,
      Dribbling: 94,
      Defending: 41,
      Physical: 77,
    },
  },
  {
    id: 6,
    name: "Robert Lewandowski",
    club: "Bayern Munich",
    nationality: "Poland",
    position: "Forward",
    statistics: {
      Overall: 91,
      Pace: 80,
      Shooting: 93,
      Passing: 79,
      Dribbling: 86,
      Defending: 40,
      Physical: 89,
    },
  },
  {
    id: 7,
    name: "Neymar Jr",
    club: "Paris Saint-Germain",
    nationality: "Brazil",
    position: "Forward",
    statistics: {
      Overall: 91,
      Pace: 91,
      Shooting: 87,
      Passing: 84,
      Dribbling: 95,
      Defending: 35,
      Physical: 75,
    },
  },
  {
    id: 8,
    name: "Mohamed Salah",
    club: "Liverpool",
    nationality: "Egypt",
    position: "Forward",
    statistics: {
      Overall: 90,
      Pace: 93,
      Shooting: 87,
      Passing: 80,
      Dribbling: 89,
      Defending: 45,
      Physical: 80,
    },
  },
  {
    id: 9,
    name: "Joshua Kimmich",
    club: "Bayern Munich",
    nationality: "Germany",
    position: "Midfielder",
    statistics: {
      Overall: 89,
      Pace: 78,
      Shooting: 82,
      Passing: 91,
      Dribbling: 86,
      Defending: 82,
      Physical: 86,
    },
  },
  {
    id: 10,
    name: "Jan Oblak",
    club: "Atletico Madrid",
    nationality: "Slovenia",
    position: "Goalkeeper",
    statistics: {
      Overall: 91,
      Pace: 60,
      Shooting: 30,
      Passing: 50,
      Dribbling: 30,
      Defending: 45,
      Physical: 89,
    },
  },
  {
    id: 11,
    name: "Sadio Mane",
    club: "Liverpool",
    nationality: "Senegal",
    position: "Forward",
    statistics: {
      Overall: 89,
      Pace: 94,
      Shooting: 85,
      Passing: 79,
      Dribbling: 88,
      Defending: 50,
      Physical: 85,
    },
  },
  {
    id: 12,
    name: "Bruno Fernandes",
    club: "Manchester United",
    nationality: "Portugal",
    position: "Midfielder",
    statistics: {
      Overall: 89,
      Pace: 77,
      Shooting: 88,
      Passing: 90,
      Dribbling: 85,
      Defending: 63,
      Physical: 81,
    },
  },
  {
    id: 13,
    name: "Harry Kane",
    club: "Tottenham Hotspur",
    nationality: "England",
    position: "Forward",
    statistics: {
      Overall: 90,
      Pace: 75,
      Shooting: 92,
      Passing: 84,
      Dribbling: 82,
      Defending: 43,
      Physical: 88,
    },
  },
  {
    id: 14,
    name: "Erling Haaland",
    club: "Borussia Dortmund",
    nationality: "Norway",
    position: "Forward",
    statistics: {
      Overall: 89,
      Pace: 87,
      Shooting: 91,
      Passing: 77,
      Dribbling: 80,
      Defending: 45,
      Physical: 87,
    },
  },
  {
    id: 15,
    name: "Alisson Becker",
    club: "Liverpool",
    nationality: "Brazil",
    position: "Goalkeeper",
    statistics: {
      Overall: 90,
      Pace: 60,
      Shooting: 30,
      Passing: 50,
      Dribbling: 30,
      Defending: 40,
      Physical: 85,
    },
  },
  {
    id: 16,
    name: "Trent Alexander-Arnold",
    club: "Liverpool",
    nationality: "England",
    position: "Defender",
    statistics: {
      Overall: 88,
      Pace: 83,
      Shooting: 78,
      Passing: 85,
      Dribbling: 83,
      Defending: 78,
      Physical: 82,
    },
  },
  {
    id: 17,
    name: "Raheem Sterling",
    club: "Manchester City",
    nationality: "England",
    position: "Forward",
    statistics: {
      Overall: 88,
      Pace: 93,
      Shooting: 84,
      Passing: 81,
      Dribbling: 90,
      Defending: 45,
      Physical: 75,
    },
  },
  {
    id: 18,
    name: "Frenkie de Jong",
    club: "Barcelona",
    nationality: "Netherlands",
    position: "Midfielder",
    statistics: {
      Overall: 88,
      Pace: 80,
      Shooting: 78,
      Passing: 88,
      Dribbling: 89,
      Defending: 79,
      Physical: 82,
    },
  },
  {
    id: 19,
    name: "Kalidou Koulibaly",
    club: "Napoli",
    nationality: "Senegal",
    position: "Defender",
    statistics: {
      Overall: 88,
      Pace: 79,
      Shooting: 50,
      Passing: 70,
      Dribbling: 60,
      Defending: 93,
      Physical: 89,
    },
  },
  {
    id: 20,
    name: "Jadon Sancho",
    club: "Manchester United",
    nationality: "England",
    position: "Forward",
    statistics: {
      Overall: 87,
      Pace: 91,
      Shooting: 83,
      Passing: 80,
      Dribbling: 89,
      Defending: 40,
      Physical: 75,
    },
  },
];
